title: fooyin Docs
description: Documentation for fooyin
theme: just-the-docs

permalink: pretty

exclude: [".vscode", ".bundle", "vendor", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"
, "CODE_OF_CONDUCT.md", "styles"]

url: https://docs.fooyin.org
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/favicon.ico"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/fooyin/fooyin-docs"
gh_edit_branch: "master"
gh_edit_view_mode: "tree"

color_scheme: dark

fooyin_version: "0.4.5"
