[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fooyin"
authors = [{name = "ludouzi", email = "luket1@proton.me"}]
dynamic = ["version", "description"]
